name = "Protagonist"
license = "MIT"
licenselink = "https://github.com/mrombout/hugo-protagonist/blob/master/LICENSE"
description = ""
homepage = "https://github.com/mrombout/hugo-protagonist/"
tags = ["minimal", "blog", "personal", "clean", "simple", "minimalist"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "Mike Rombout"
  homepage = "https://mikero.nl"
